# Data Cleaning & Preprocessing
This notebook focuses on cleaning and preprocessing the dataset to improve data quality and prepare it for further analysis and forecasting tasks.

Import libraries

In [2]:
import numpy as np
import pandas as pd

Load & inspect data

In [32]:
df = pd.read_csv(r'C:\PlantNxt Assignment\data\raw\revenue_ledger.csv')
df.head()

,Account,Cust Code,Part Code,Inv Date,Quantity,Price,Tax,Others
0,Account A,Cust-00762,Part-01473,2022-04-01,3.0,"9,787.10","8,415.52",694.14
1,Account A,Cust-00762,Part-01473,2022-04-01,10.0,"9,787.10","28,051.74","2,313.80"
2,Account A,Cust-00519,Part-01675,2022-04-01,18.6,"46,045.00","1,54,158.66","10,105.96"
3,Account A,Cust-00302,Part-01312,2022-04-01,5.0,"4,761.14","4,570.44","1,585.65"
4,Account A,Cust-00302,Part-01573,2022-04-01,5.0,"4,752.34","4,562.52","1,585.65"

In [33]:
df.tail()

,Account,Cust Code,Part Code,Inv Date,Quantity,Price,Tax,Others
234511,Account B,Cust-00265,Part-00241,2026-05-16,180.0,327.62,NaN,0.00
234512,Account B,Cust-00320,Part-00215,2026-05-16,596.5,242.86,NaN,0.00
234513,Account B,Cust-00320,Part-00215,2026-05-16,1800.0,315.86,NaN,0.00
234514,Account B,Cust-00233,Part-00138,2026-05-16,3000.0,299.25,NaN,0.00
234515,Account B,Cust-00630,Part-00289,2026-05-16,2400.0,332.33,NaN,0.00

In [34]:
print(f"Rows: {df.shape[0]}")
print(f"Columns: {df.shape[1]}")

Rows: 234516
Columns: 8

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 234516 entries, 0 to 234515
Data columns (total 8 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   Account    234516 non-null  object
 1   Cust Code  234516 non-null  object
 2   Part Code  234516 non-null  object
 3   Inv Date   234516 non-null  object
 4   Quantity   234516 non-null  float64
 5   Price      234516 non-null  object
 6   Tax        209310 non-null  object
 7   Others     221748 non-null  object
dtypes: float64(1), object(7)
memory usage: 14.3+ MB

In [36]:
df.dtypes

Account       object
Cust Code     object
Part Code     object
Inv Date      object
Quantity     float64
Price         object
Tax           object
Others        object
dtype: object

Datatype conversion

In [37]:
columns = ['Price', 'Tax', 'Others']

for col in columns:
    df[col] = df[col].astype(str).str.replace(',', '').str.strip()
    df[col] = pd.to_numeric(df[col], errors='coerce')

df['Inv Date'] = pd.to_datetime(df['Inv Date'])
df['Quantity'] = pd.to_numeric(df['Quantity'], errors='coerce')

In [38]:
df.dtypes

Account              object
Cust Code            object
Part Code            object
Inv Date     datetime64[ns]
Quantity            float64
Price               float64
Tax                 float64
Others              float64
dtype: object

Null value Handling

In [39]:
df.isna().sum()

Account          0
Cust Code        0
Part Code        0
Inv Date         0
Quantity         0
Price            0
Tax          25206
Others       12768
dtype: int64

In [40]:
(df.isna().sum()/len(df)) * 100

Account       0.000000
Cust Code     0.000000
Part Code     0.000000
Inv Date      0.000000
Quantity      0.000000
Price         0.000000
Tax          10.748094
Others        5.444405
dtype: float64

In [41]:
df['Others'] = df['Others'].fillna(df['Others'].mean())
df['Tax'] = df['Tax'].fillna(df['Tax'].mean())

Handling duplicates

In [48]:
print(f"No: of duplicates: {df.duplicated().sum()}")
print(f"% of duplicates: {df.duplicated().sum()/len(df) * 100: .2f}%")

No: of duplicates: 34278
% of duplicates:  14.62%

In [51]:
df[df.duplicated()].head()

,Account,Cust Code,Part Code,Inv Date,Quantity,Price,Tax,Others
17,Account A,Cust-00274,Part-01646,2022-04-01,10.0,4278.6,8026.20,1804.0
18,Account A,Cust-00274,Part-01645,2022-04-01,10.0,4259.1,7991.10,1804.0
23,Account A,Cust-00274,Part-01646,2022-04-01,10.0,4278.6,8026.20,1804.0
24,Account A,Cust-00274,Part-01645,2022-04-01,10.0,4259.1,7991.10,1804.0
33,Account A,Cust-00274,Part-01626,2022-04-01,5.0,4384.2,4044.78,550.0

In [54]:
df = df.drop_duplicates()
df = df.reset_index(drop=True)
df.shape

(200238, 8)

save the cleaned data

In [56]:
df.to_csv(r'C:\PlantNxt Assignment\data\processed\data.csv', index = False)